export enum ActionDecisionEnum {
  OUT_AWAY = 'OUT_AWAY',
  SHORT_PASS = 'SHORT_PASS',
  LONG_PASS = 'LONG_PASS',
  HOLD = 'HOLD',
  DRIBBLING = 'DRIBBLING',
  CLOSE_BLANK_SHOT = 'CLOSE_BLANK_SHOT',
  DRIBBLING_GOALKEEPER = 'DRIBBLING_GOALKEEPER',
  MIDDLE_SHOT = 'MIDDLE_SHOT',
  LONG_SHOT = 'LONG_SHOT',
  CROSSING = 'CROSSING',
}

export enum ActionZoneEnum {
  SMALL_AREA = 'SMALL_AREA',
  BIG_AREA = 'BIG_AREA',
  LATERAL_AREA = 'LATERAL_AREA',
  PRE_AREA = 'PRE_AREA',
  LATERAL_MID_FIELD = 'LATERAL_MID_FIELD',
  MID_FIELD_CENTER = 'MID_FIELD_CENTER',
}

export enum AbstractFieldZoneEnum {
  CORNER_UP = 'CORNER_UP',
  CORNER_DOWN = 'CORNER_DOWN',
  AREA = 'AREA',
}

export enum EventZoneEnum {
  CORNER = 'CORNER',
  PENALTY = 'PENALTY',
}

export enum ActionSide {
  ATTACK = 'Attack',
  DEFENSE = 'Defense',
}
